#!/usr/bin/env node
// Scans modules/ and generates the UI's module-frontend registry so first-party
// panels are statically bundled by Vite. Re-run on add/remove of a module.
import { readdirSync, existsSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, relative } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const modulesDir = resolve(root, "modules");
const outFile = resolve(root, "packages/ui/src/modules.generated.ts");

const FRONTEND_EXTS = [".tsx", ".jsx", ".ts", ".js"];

function frontendFile(dir) {
  for (const ext of FRONTEND_EXTS) {
    const p = resolve(dir, "frontend" + ext);
    if (existsSync(p)) return p;
  }
  return undefined;
}

const found = [];
if (existsSync(modulesDir)) {
  for (const name of readdirSync(modulesDir)) {
    const dir = resolve(modulesDir, name);
    if (!statSync(dir).isDirectory()) continue;
    const fe = frontendFile(dir);
    if (fe) {
      const rel = relative(dirname(outFile), fe).replaceAll("\\", "/");
      found.push({ name, importPath: rel.startsWith(".") ? rel : "./" + rel });
    }
  }
}

const imports = found.map((m, i) => `import m${i} from "${m.importPath}";`).join("\n");
const entries = found.map((m, i) => `  ${JSON.stringify(m.name)}: m${i},`).join("\n");

const out = `// AUTO-GENERATED by packages/tooling/gen-modules.mjs — do not edit.
import type { ModuleFrontend } from "@hub/sdk";
${imports}

export const moduleFrontends: Record<string, ModuleFrontend> = {
${entries}
};
`;

writeFileSync(outFile, out);
console.log(`[gen-modules] wrote ${found.length} frontend(s) -> ${relative(root, outFile)}`);
